version: '3' # docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 80:80
      - 443:443 # for future ssl traffid
  db:
    image: mysql:latest
    environment:
      # MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE=edoc
      - MYSQL_USER=root
      - MYSQL_PASSWORD= # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # sync persistent sql files with container
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306